version: '3.8'

services:
  epusdt:
    build: .
    container_name: epusdt
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./runtime:/app/runtime
    depends_on:
      - mysql
      - redis
    networks:
      - epusdt_net

  mysql:
    image: mysql:5.7
    container_name: epusdt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: epusdt
      MYSQL_USER: epusdt
      MYSQL_PASSWORD: epusdtpassword
      TZ: Asia/Shanghai  # 添加时区配置
    command: 
      - --wait_timeout=28800
      - --interactive_timeout=28800
    volumes:
      - ./sql/epusdt.sql:/docker-entrypoint-initdb.d/epusdt.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - epusdt_net

  redis:
    image: redis:alpine
    container_name: epusdt_redis
    environment:
      REDIS_PASSWORD: liuchen123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - epusdt_net

volumes:
  mysql_data:
  redis_data:

networks:
  epusdt_net:
    driver: bridge